### PR TITLE
fixed issue where children cannot work when empty

### PR DESCRIPTION
**Pull request by chenshuai2144**
When getting tableOfContents in my project, sometimes I get an error: 
`"TypeError: Cannot read property 'length' of undefined",`

this pr can solve the problem

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Thanks @chenshuai2144!
From the diff, the change looks good.
Is there a test case you could share or include that demostrates the fix?

**Comment by chenshuai2144** [comment]
sorry, I do n’t have the smallest reproduction.
I only know that he has something to do with table of contents

**Comment by wooorm** [comment]
Hi there! This is a problem because you are using a plugin or utility that creates non-conforming mdast: `link` and `linkReference` should have a children.

> sorry, I do n’t have the smallest reproduction.

So this is a bug somewhere in the tools that you are using. We really can’t help you if we have no clue what you are doing. What are you using? Gatsby? Something to do with headings?

**Comment by wooorm** [comment]
I’m closing this: this is a bug in the other things you’re using. It’s surfacing here, but it could just as well surface in other utilities. It’s best to focus on fixing the bug’s root cause, not the symptoms

**Pull request closed without merging**
